version: '2'

services:
  mysql:
    image: mysql
    container_name: db-mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - /storage/docker/mysql-datadir:/var/lib/mysql